# Generated by Django 3.2.16 on 2022-12-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albumapp', '0002_rename_e_name_engagement_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engagement',
            old_name='name',
            new_name='e_name',
        ),
    ]
