# Generated by Django 3.2.16 on 2022-12-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albumapp', '0003_rename_name_engagement_e_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='e_name',
        ),
    ]
