# Generated by Django 3.2.16 on 2022-12-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumapp', '0004_remove_engagement_e_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mk_sreya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk_sreya_img', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
