# Generated by Django 3.2.16 on 2022-12-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumapp', '0005_mk_sreya'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mk_sethu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk_sethu_img', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wedding_img', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
